### PR TITLE
CI/CD: clarify stages/jobs naming

### PR DESCRIPTION
**Pull request by zabbal**

### CODE REVIEW

**Comment by simao** [comment]
When do you want this to run?

**Comment by zabbal** [comment]
> When do you want this to run?

What do you mean by "this"?

**Comment by simao** [comment]
The pipeline

**Comment by zabbal** [comment]
There're 3 pipelines touched by this patch. Two of those could only be triggered via schedule. One can only be triggered if particular variable is defined. So far this variable been defined as part of the schedule as well.

**Comment by simao** [comment]
There is one pipeline to which you are adding 3 stages, when do you want those stages to run?

**Comment by zabbal** [comment]
Ah, right, there're actually 2 pipelines spread over 3 stages. Nevertheless, it's all meant to run via schedule.

**Comment by simao** [comment]
Where is the 2nd pipeline?

**Comment by zabbal** [comment]
pipeline 1: "start deps scan" -> "generate pages"
pipeline 2: "start veracode scan"

**Comment by simao** [comment]
There is only one pipeline that contains different stages, which contains different jobs that are either activated or not depending on the conditions we put on them

**Pull request merged**
