### PR TITLE
[OTA-3179] Correctly parse a CSV exported from a spreadsheet

### PR DESCRIPTION
**Pull request by houcros**
The current implementation fails because exporting as CSV from a spreadsheet application doesn't add a line break after the last record.

### CODE REVIEW

**Comment by houcros** [comment]
The build fails for now because we need to merge this first: https://github.com/advancedtelematic/libats/pull/112

**Comment by nkly** [comment]
Maybe it would be better to split Akka bumping and CSV fixing into separate PRs?

**Comment by houcros** [comment]
Fair enough, will do.

**Comment by houcros** [comment]
Opened #101.

**Pull request merged**
